add_subdirectory(test_textfolding)
add_subdirectory(test_utils)
add_subdirectory(test_markdownparser)
add_subdirectory(test_cmark_probe)
add_subdirectory(test_goldenmaster)
add_subdirectory(test_benchmark)
add_subdirectory(test_astwalker)
add_subdirectory(test_markdownfolding)
add_subdirectory(test_theme)
add_subdirectory(test_tablepreview)
add_subdirectory(test_tablepreviewinputmode)
add_subdirectory(test_interactivepreview)
add_subdirectory(test_previewbenchmark)
add_subdirectory(test_previewscrollstability)
add_subdirectory(test_richtexteditor)
add_subdirectory(test_markdowneditor)
